project:
  type: website
  output-dir: docs
  resources:
    - images

website:
  sidebar:
    title: "fabianzoefelt"
    logo: images/Logo.png
    style: docked
    search: true
    contents:
      - text: "Start"
        href: index.qmd
      - text: "About me"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Output"
        href: scientific-output.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    center: "© 2026 Fabian Zöfelt"

format:
  html:
    theme: cosmo
    toc: true
    css: styles-FZ.css
    header-includes:
      - '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">'


